services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    links:
      - loki
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_volume_self:/var/lib/grafana/
    depends_on:
      - prometheus

volumes:
  grafana_volume_self:
